import { Metadata } from 'next';
import './styles/global.css';
import Nav from './components/nav';

export const metadata: Metadata = {
  title: {
    template: '%s | Next Movie',
    default: 'Loading...',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ paddingTop: '100px' }}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
